version: "3"

services:
  http:
    build: 
      context: ./bin/webserver
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ${DOCUMENT_ROOT-./htdocs}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
